spring:
  profiles:
    include: mongo

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my.dragon.com:3306/springboot
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

