server:
  port: 8080
  context-path: /MyBlog

# 配置thymeleaf
spring:
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  #Druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MyBlog?characterEncoding=utf8
    username: root
    password: 123
    #初始化大小
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #配置获取连接等待超时时间
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位为毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个链接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #配置监控统计拦截的filters,去掉监控界面sql将无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #通过connectProperties属性来打开mergeSql功能，慢sql记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    # useGlobalDataSourceStat=true

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


  output:
    ansi:
      enabled: detect

# 将日志输出的最高级别置成debug
debug: true

logging:
  # 设置日志输出文件
  file: logs/MyBlog.log
  # 设置日志文件输出格式
  pattern:
      file: .%d{HH:mm:ss.SSS}  [%thread] %-5level %logger{36} - %msg %n


  #配置Mybatis
#  mybatis:
#    mapperLocations: classpath:mapper/*.xml
#    typeAliasesPackage: hht.dragon.entity

